import type { Metadata } from "next";
import { Bricolage_Grotesque, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "./Components/Shared/Header";

const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display: "swap",
});

export const metadata: Metadata = {
  title: "CSE Academic Solutions",
  description: "Generated by All Info Zone ",
};

import { MusicProvider } from "./Context/MusicContext";
import MiniPlayer from "./Components/Music/MiniPlayer";
import Footer from "./Components/Shared/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning>
      <body className={`${bricolageGrotesque.variable} ${spaceGrotesk.variable} antialiased bg-[#525333] min-h-screen relative`}>
        {/* 70s Film Grain Overlay */}
        <div 
          className="pointer-events-none fixed inset-0 z-50 opacity-[0.22] mix-blend-overlay"
          style={{
            backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.75' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")`,
          }}
        />
        
        {/* Optional: Faded Paper Wash (Gives it that 70s warm tint) */}
        <div className="pointer-events-none fixed inset-0 z-40 bg-orange-900/5 mix-blend-multiply" />

        <MusicProvider>
          <Header />
            <div className="relative z-10 transition-opacity duration-700">
               {children}
            </div>
          <Footer />
          <MiniPlayer />
        </MusicProvider>
      </body>
    </html>
  );
}
